
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MyWebsite
{

using System;
    using System.Collections.Generic;
    
public partial class Education
{

    public int EducationID { get; set; }

    public int PersonID { get; set; }

    public string DegreeName { get; set; }

    public System.DateTime GraduationDate { get; set; }

    public string Major { get; set; }

    public decimal Percentage { get; set; }

    public string InstitutionName { get; set; }

    public string SpecializedConcentrations { get; set; }



    public virtual Person Person { get; set; }

}

}
