
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MyWebsite
{

using System;
    using System.Collections.Generic;
    
public partial class Hobby
{

    public int PersonID { get; set; }

    public int HobbiesID { get; set; }

    public string Hobbies { get; set; }



    public virtual Person Person { get; set; }

}

}
