
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MyWebsite
{

using System;
    using System.Collections.Generic;
    
public partial class Project
{

    public int PersonID { get; set; }

    public int ProjectID { get; set; }

    public string ProjectName { get; set; }

    public string ProjectDescription { get; set; }

    public int TeamSize { get; set; }

    public string Role { get; set; }



    public virtual Person Person { get; set; }

}

}
