

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MyWebsite
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class StudentEntities : DbContext
{
    public StudentEntities()
        : base("name=StudentEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Address> Addresses { get; set; }

    public virtual DbSet<Certification> Certifications { get; set; }

    public virtual DbSet<Education> Educations { get; set; }

    public virtual DbSet<Hobby> Hobbies { get; set; }

    public virtual DbSet<Interest> Interests { get; set; }

    public virtual DbSet<Person> People { get; set; }

    public virtual DbSet<Phone> Phones { get; set; }

    public virtual DbSet<Project> Projects { get; set; }

    public virtual DbSet<Skill> Skills { get; set; }

    public virtual DbSet<Url> Urls { get; set; }

    public virtual DbSet<Work> Works { get; set; }

    public virtual DbSet<Tracker> Trackers { get; set; }

}

}

