
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MyWebsite
{

using System;
    using System.Collections.Generic;
    
public partial class Tracker
{

    public int TrackingID { get; set; }

    public string TrackingInfo { get; set; }

    public Nullable<System.DateTime> LastVisitedOn { get; set; }

    public Nullable<int> NoOfHits { get; set; }

    public string IpAddress { get; set; }

}

}
