
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MyWebsite
{

using System;
    using System.Collections.Generic;
    
public partial class Work
{

    public int PersonID { get; set; }

    public int WorkID { get; set; }

    public string Role { get; set; }

    public string Duration { get; set; }

    public string Duties { get; set; }

    public string ReasonForLeaving { get; set; }

    public string Company { get; set; }

    public string Location { get; set; }

    public string Expertise { get; set; }

    public string Accomplishments { get; set; }



    public virtual Person Person { get; set; }

}

}
